sudo: required
language: python
services: docker
python:
    - "3.6"
cache:
    - pip3
# blocklist
branches:
  except:
    - broken
before_install:
    - echo "Build directory = "$TRAVIS_BUILD_DIR
    - docker build --build-arg BUILD_DIR=$TRAVIS_BUILD_DIR -t nicolashainaux/mathmaker .
install:
    - pip3 install coveralls
script:
    - docker run --name affectionate_carson nicolashainaux/mathmaker /bin/bash -c "cd ${TRAVIS_BUILD_DIR} && coverage run --source=mathmaker setup.py test"
after_success:
    - docker cp affectionate_carson:${TRAVIS_BUILD_DIR}/.coverage .coverage
    - coveralls
