sudo: required
language: python
services: docker
python:
    - "3.6"
cache:
    - pip3
# blocklist
branches:
  except:
    - broken
before_install:
    - docker pull zezollo/mathmaker:ubuntu17.10
script:
    - docker run zezollo/mathmaker:ubuntu17.10 /bin/bash -c "cd /build && coverage run --source=mathmaker setup.py test"
after_success:
    - docker exec zezollo/mathmaker:ubuntu17.10 /bin/bash -c "cd /build/ && coveralls"
