sudo: required
language: python
services: docker
python:
    - "3.6"
cache:
    - pip3
# blocklist
branches:
  except:
    - broken
before_install:
    - docker build -t nicolashainaux/mathmaker .
script:
    - docker run -d nicolashainaux/mathmaker /bin/bash -c "coverage run pytest -x -vv -r w /build/"
after_success:
    - docker run -d nicolashainaux/mathmaker /bin/bash -c "cd /build/ ; coveralls"
