sudo: required
language: python
services: docker
python:
    - "3.6"
cache:
    - pip3
# blocklist
branches:
  except:
    - broken
before_install:
    - docker build -t nicolashainaux/mathmaker .
install:
    - pip3 install coveralls
script:
    - docker run --name affectionate_carson nicolashainaux/mathmaker /bin/bash -c "cd /home/travis/build/nicolashainaux/mathmaker && coverage run --source=mathmaker setup.py test"
after_success:
    - docker cp affectionate_carson:/home/travis/build/nicolashainaux/mathmaker/.coverage .coverage
    - coveralls
