sudo: required
language: python
services: docker
python:
    - "3.6"
cache:
    - pip3
# blocklist
branches:
  except:
  - broken
before_install:
  - docker build -t nicolashainaux/mathmaker .
install:
  - docker run -d nicolashainaux/mathmaker /bin/bash -c "cd /build/ ; pip3 install --force -r requirements.txt --extra-index-url https://mirror.picosecond.org/pypi/simple ; pip3 install coverage coveralls"
script:
    - "coverage run --source=mathmaker setup.py test"
after_success:
    coveralls
