sudo: required
language: python
services: docker
python:
    - "3.6"
cache:
    - pip3
# blocklist
branches:
  except:
    - broken
before_install:
    - mkdir /build
    - docker build -t nicolashainaux/mathmaker .
install:
    - "pip3 install coveralls"
script:
    - docker run --name affectionate_carson nicolashainaux/mathmaker /bin/bash -c "cd /build && coverage run --source=mathmaker setup.py test"
    - docker cp affectionate_carson:/build/.coverage .coverage
    - docker cp affectionate_carson:/build/mathmaker /build/mathmaker
after_success:
    - coveralls
    # - coverage combine
    # - docker start affectionate_carson && docker exec -e CI="$CI" -e TRAVIS="$TRAVIS" -e CONTINUOUS_INTEGRATION="$CONTINUOUS_INTEGRATION" -e DEBIAN_FRONTEND="$DEBIAN_FRONTEND" -e USER="$USER" -e TRAVIS_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" affectionate_carson /bin/bash -c "ls -al /build/ && coveralls -d /build/.coverage -b /build/"
