version: build{build}

branches:
  only:
  - master
  - pre-release
  - dev

image:
  - Ubuntu2004

max_jobs: 1

environment:
  PYTHONWARNINGS: ignore
  APPVEYOR_BAKE_IMAGE: ubuntu2004_mathmaker

install:
  # We need wheel installed to build wheels
  - sh: sudo apt -qq update
  - sh: sudo apt -y install libxml2-utils eukleides gettext python3-pip texlive-latex-base texlive-luatex texlive-xetex texlive-pstricks texlive-font-utils texlive-latex-extra texlive-base texlive-science texlive-pictures texlive-latex-recommended texlive-fonts-recommended texlive-fonts-extra locales

build:
  - sh: sudo locale-gen en_US.UTF-8 && sudo locale-gen fr_FR.UTF-8
  - sh: curl -sSL https://install.python-poetry.org | python3 -
  - sh: export PATH="$HOME/.local/bin:$PATH"
  - sh: poetry install

test_script:
  - sh: poetry run coverage run --source=mathmaker -m pytest -vv

# after_test:
#   # This step builds your wheels.

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  #- path: dist\*

on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
  - sh: poetry run coveralls
