#!/bin/sh

# This function will replace the default headers by more appropriated ones.
# It takes $1 as the file name
# $2 as the title to insert
set_header () {

    sed -i 's/Copyright (C) YEAR/Copyright (C) 2006-'`date +%Y`'/' "$1"
    sed -i 's/This file is distributed under the same license as the PACKAGE package/This file is distributed under the same license as the mathmaker package/' "$1"
    sed -i 's/SOME DESCRIPTIVE TITLE/'"$2"'/' "$1"
    sed -i 's/charset=CHARSET/charset=UTF-8/' "$1"

}

cd ..

PROJ_DIR=`pwd`
ROOT_DIR=$PROJ_DIR"/mathmaker"

echo $ROOT_DIR

cd mathmaker/
xgettext --package-name="mathmaker" --package-version="0.6" --copyright-holder="Nicolas Hainaux" --msgid-bugs-address="nh.techn@gmail.com" --keyword=_ --output=locale/mathmaker_updates.pot *.py */*.py */*/*.py */*/*/*.py */*/*/*/*.py */*/*/*/*/*.py

../tools/merge_py_updates_to_main_pot_file

echo

# Merging mathmaker entries to main pot file:
../tools/merge_xml_updates_to_pot_file --dirs "$ROOT_DIR""/data/"

# Merging updates from other xml files to other pot files
#./merge_xml_updates_to_pot_file --keywords w4l --dir "$ROOT_DIR""/data/w4l" --potfile "$ROOT_DIR""/locale/w4l.pot"
#./merge_xml_updates_to_pot_file --keywords name --dir "$ROOT_DIR""/data/names/f/" --potfile "$ROOT_DIR""/locale/names_f.pot"
#./merge_xml_updates_to_pot_file --keywords name --dir "$ROOT_DIR""/data/names/m/" --potfile "$ROOT_DIR""/locale/names_m.pot"

#set_header mathmaker.pot 'MATHMAKER TEMPLATE PO FILE'
#set_header four_letters_words.pot 'MATHMAKER W4L PO FILE'

echo "Removing mathmaker_updates.pot"
rm ./locale/mathmaker_updates.pot