#!/bin/sh

cd ..
xgettext --package-name="mathmaker" --package-version="0.6" --copyright-holder="Nicolas Hainaux" --msgid-bugs-address="nh.techn@gmail.com" --keyword=_ --output=locale/mathmaker.pot */*.py */*/*.py */*/*/*.py */*/*/*/*.py
cd locale/
./add_strings_from_xml_files
sed -i "s/Copyright (C) YEAR/Copyright (C) 2006-"`date +%Y`"/" mathmaker.pot
sed -i "s/This file is distributed under the same license as the PACKAGE package/This file is distributed under the same license as the mathmaker package/" mathmaker.pot
sed -i "s/SOME DESCRIPTIVE TITLE/MATHMAKER TEMPLATE PO FILE/" mathmaker.pot
sed -i "s/charset=CHARSET/charset=UTF-8/" mathmaker.pot
