#!/bin/sh

# This function will replace the default headers by more appropriated ones.
# It takes $1 as the file name
# $2 as the title to insert
set_header () {

    sed -i 's/Copyright (C) YEAR/Copyright (C) 2006-'`date +%Y`'/' "$1"
    sed -i 's/This file is distributed under the same license as the PACKAGE package/This file is distributed under the same license as the mathmaker package/' "$1"
    sed -i 's/SOME DESCRIPTIVE TITLE/'"$2"'/' "$1"
    sed -i 's/charset=CHARSET/charset=UTF-8/' "$1"

}

cd ..
xgettext --package-name="mathmaker" --package-version="0.6" --copyright-holder="Nicolas Hainaux" --msgid-bugs-address="nh.techn@gmail.com" --keyword=_ --output=locale/mathmaker_updates.pot */*.py */*/*.py */*/*/*.py */*/*/*/*.py */*/*/*/*/*.py

cd locale/

./merge_py_updates_to_main_pot_file

echo "Removing mathmaker_updates.pot"
rm mathmaker_updates.pot
echo

# Merging mathmaker entries to main pot file:
./merge_xml_updates_to_pot_file --dir /home/nico/dev/mathmaker/mathmaker/sheet/

# Merging updates from other xml files to other pot files
#./merge_xml_updates_to_pot_file --keywords w4l --dir /home/nico/dev/mathmaker/mathmaker/locale/xml_additions/w4l/ --potfile /home/nico/dev/mathmaker/mathmaker/locale/w4l.pot
#./merge_xml_updates_to_pot_file --keywords name --dir /home/nico/dev/mathmaker/mathmaker/locale/xml_additions/names/f/ --potfile /home/nico/dev/mathmaker/mathmaker/locale/names_f.pot
#./merge_xml_updates_to_pot_file --keywords name --dir /home/nico/dev/mathmaker/mathmaker/locale/xml_additions/names/m/ --potfile /home/nico/dev/mathmaker/mathmaker/locale/names_m.pot

#set_header mathmaker.pot 'MATHMAKER TEMPLATE PO FILE'
#set_header four_letters_words.pot 'MATHMAKER W4L PO FILE'
